# Generated by Django 5.2.1 on 2025-06-03 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='listening/videos/')),
                ('instructions', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListeningTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('vertical', models.IntegerField(choices=[(1, 'Quality Assurance Engineers'), (2, 'Cybersecurity'), (3, 'Digital Marketing'), (4, 'Vertical Testing'), (5, 'Data & BI'), (6, 'Test'), (7, 'UX/UI & Product Management'), (8, 'Sales'), (9, 'Software Engineer'), (10, 'Journalism, Broadcasting, and Public Relations'), (13, 'Finanzas y Contaduría'), (14, 'Negocios y Administración'), (15, 'Human Resources')])),
            ],
        ),
        migrations.CreateModel(
            name='ListeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(default='multiple_choice', max_length=50)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.listeningblock')),
            ],
        ),
        migrations.CreateModel(
            name='ListeningOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=300)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.listeningquestion')),
            ],
        ),
        migrations.AddField(
            model_name='listeningblock',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.listeningtest'),
        ),
    ]
