# Generated by Django 5.2.1 on 2025-06-04 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('vertical', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Speaking Test',
                'verbose_name_plural': 'Speaking Tests',
            },
        ),
        migrations.CreateModel(
            name='SpeakingBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('instruction', models.TextField()),
                ('example', models.TextField()),
                ('speaking_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_blocks', to='core.speakingtest')),
            ],
            options={
                'verbose_name': 'Speaking Block',
                'verbose_name_plural': 'Speaking Blocks',
            },
        ),
    ]
