# Generated by Django 5.2.1 on 2025-06-04 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_speakingtest_speakingblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Reading Block',
                'verbose_name_plural': 'Reading Blocks',
            },
        ),
        migrations.CreateModel(
            name='ReadingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('vertical', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Reading Test',
                'verbose_name_plural': 'Reading Tests',
            },
        ),
        migrations.CreateModel(
            name='ReadingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('reading_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.readingblock')),
            ],
            options={
                'verbose_name': 'Reading Question',
                'verbose_name_plural': 'Reading Questions',
            },
        ),
        migrations.CreateModel(
            name='ReadingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.readingquestion')),
            ],
            options={
                'verbose_name': 'Reading Option',
                'verbose_name_plural': 'Reading Options',
            },
        ),
        migrations.AddField(
            model_name='readingblock',
            name='reading_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_blocks', to='core.readingtest'),
        ),
    ]
