# Generated by Django 5.2.1 on 2025-06-04 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_readingblock_readingtest_readingquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('vertical', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Writing Test',
                'verbose_name_plural': 'Writing Tests',
            },
        ),
        migrations.CreateModel(
            name='WritingBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('instruction', models.TextField()),
                ('example', models.TextField()),
                ('writing_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_blocks', to='core.writingtest')),
            ],
            options={
                'verbose_name': 'Writing Block',
                'verbose_name_plural': 'Writing Blocks',
            },
        ),
    ]
