# Generated by Django 5.2.1 on 2025-06-07 00:22

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_writingtest_writingblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningblock',
            name='video_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='readingtest',
            name='vertical',
            field=models.IntegerField(choices=[(1, 'Quality Assurance Engineers'), (2, 'Cybersecurity'), (3, 'Digital Marketing'), (4, 'Vertical Testing'), (5, 'Data & BI'), (6, 'Test'), (7, 'UX/UI & Product Management'), (8, 'Sales'), (9, 'Software Engineer'), (10, 'Journalism, Broadcasting, and Public Relations'), (13, 'Finanzas y Contaduría'), (14, 'Negocios y Administración'), (15, 'Human Resources')]),
        ),
        migrations.AlterField(
            model_name='speakingtest',
            name='vertical',
            field=models.IntegerField(choices=[(1, 'Quality Assurance Engineers'), (2, 'Cybersecurity'), (3, 'Digital Marketing'), (4, 'Vertical Testing'), (5, 'Data & BI'), (6, 'Test'), (7, 'UX/UI & Product Management'), (8, 'Sales'), (9, 'Software Engineer'), (10, 'Journalism, Broadcasting, and Public Relations'), (13, 'Finanzas y Contaduría'), (14, 'Negocios y Administración'), (15, 'Human Resources')]),
        ),
        migrations.AlterField(
            model_name='writingtest',
            name='vertical',
            field=models.IntegerField(choices=[(1, 'Quality Assurance Engineers'), (2, 'Cybersecurity'), (3, 'Digital Marketing'), (4, 'Vertical Testing'), (5, 'Data & BI'), (6, 'Test'), (7, 'UX/UI & Product Management'), (8, 'Sales'), (9, 'Software Engineer'), (10, 'Journalism, Broadcasting, and Public Relations'), (13, 'Finanzas y Contaduría'), (14, 'Negocios y Administración'), (15, 'Human Resources')]),
        ),
    ]
