# Generated by Django 5.2.1 on 2025-06-07 00:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_listeningblock_video_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningblock',
            name='video_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
    ]
