# Generated by Django 5.2.1 on 2025-06-10 01:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_listeningblock_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('vertical', models.IntegerField(choices=[(1, 'Quality Assurance Engineers'), (2, 'Cybersecurity'), (3, 'Digital Marketing'), (4, 'Vertical Testing'), (5, 'Data & BI'), (6, 'Test'), (7, 'UX/UI & Product Management'), (8, 'Sales'), (9, 'Software Engineer'), (10, 'Journalism, Broadcasting, and Public Relations'), (13, 'Finanzas y Contaduría'), (14, 'Negocios y Administración'), (15, 'Human Resources')])),
                ('resultado_listening', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('resultado_speaking', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('resultado_writing', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('resultado_reading', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('resultado_general', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('nivel', models.CharField(blank=True, choices=[('principiante', 'Principiante'), ('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=20, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
