# Generated by Django 5.2.1 on 2025-06-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningtest',
            name='vertical',
            field=models.IntegerField(choices=[(1, 'Quality Assurance Engineers'), (2, 'Cybersecurity'), (3, 'Digital Marketing'), (7, 'UX/UI & Product Management'), (8, 'Sales'), (9, 'Software Engineer'), (5, 'Data & BI'), (13, 'Finanzas y Contaduría'), (14, 'Negocios y Administración'), (15, 'Human Resources')]),
        ),
        migrations.AlterField(
            model_name='readingtest',
            name='vertical',
            field=models.IntegerField(choices=[(1, 'Quality Assurance Engineers'), (2, 'Cybersecurity'), (3, 'Digital Marketing'), (7, 'UX/UI & Product Management'), (8, 'Sales'), (9, 'Software Engineer'), (5, 'Data & BI'), (13, 'Finanzas y Contaduría'), (14, 'Negocios y Administración'), (15, 'Human Resources')]),
        ),
        migrations.AlterField(
            model_name='speakingtest',
            name='vertical',
            field=models.IntegerField(choices=[(1, 'Quality Assurance Engineers'), (2, 'Cybersecurity'), (3, 'Digital Marketing'), (7, 'UX/UI & Product Management'), (8, 'Sales'), (9, 'Software Engineer'), (5, 'Data & BI'), (13, 'Finanzas y Contaduría'), (14, 'Negocios y Administración'), (15, 'Human Resources')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nivel',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='vertical',
            field=models.IntegerField(choices=[(1, 'Quality Assurance Engineers'), (2, 'Cybersecurity'), (3, 'Digital Marketing'), (7, 'UX/UI & Product Management'), (8, 'Sales'), (9, 'Software Engineer'), (5, 'Data & BI'), (13, 'Finanzas y Contaduría'), (14, 'Negocios y Administración'), (15, 'Human Resources')]),
        ),
        migrations.AlterField(
            model_name='writingtest',
            name='vertical',
            field=models.IntegerField(choices=[(1, 'Quality Assurance Engineers'), (2, 'Cybersecurity'), (3, 'Digital Marketing'), (7, 'UX/UI & Product Management'), (8, 'Sales'), (9, 'Software Engineer'), (5, 'Data & BI'), (13, 'Finanzas y Contaduría'), (14, 'Negocios y Administración'), (15, 'Human Resources')]),
        ),
    ]
