# Generated by Django 5.2.1 on 2025-06-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='intentos_realizados',
            field=models.IntegerField(default=0),
        ),
    ]
