# Generated by Django 5.2.1 on 2025-06-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fecha_bloqueo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
